
version: '3'

services:
    monitor:
        restart: always
        build: .
        command: "npm run app"
        env_file:
            - .env-file
        ports:
            - "3000:3000"
        networks:
            - netto

networks:
  netto:


